### ISSUE TITLE
Firefox alternative?

### ISSUE THREAD

**Issue by Long-Horse** [agschwender/reddited-extension#12]
Is it possible this can be ported to Firefox?

**Comment by agschwender** [comment]
I'm not really interested in doing a port of this. But here's some alternatives that are on firefox:

https://addons.mozilla.org/en-US/firefox/addon/socialite/
https://addons.mozilla.org/en-US/firefox/addon/reddited/

Probably a few more, but I don't use firefox so I'm not too familiar with firefox add-ons. 

That said, you're more than welcome to make a port of it if it's something that you're interested in doing.

**Comment by Long-Horse** [comment]
There are a few alternatives but none compare to your masterpiece :/
