### ISSUE TITLE
Feature request: blacklist

### ISSUE THREAD

**Issue by Long-Horse** [agschwender/reddited-extension#9]
The options are "Never", "Always" & "For Listed Domains". Can we have an option for "All Domains Except:"

**Comment by agschwender** [comment]
Fixed in 1.3.18

**Comment by Long-Horse** [comment]
Thanks! Wasn't really expecting it to be done (let alone in 1 day) after not being updated in a long time.

**Comment by agschwender** [comment]
Yeah, I don't ever look at the chrome web store, but I'm on github all the time. So I try to be pretty responsive to requests posted here for projects I work on.
